/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/bfae1fb1-62a4-4a11-8e5a-638f425bcb6d 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool lED;
  bool sunlight;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "arduino_secrets.h"
#include <BH1750FVI.h>
#include "thingProperties.h"

BH1750FVI LightSensor(BH1750FVI::k_DevModeContLowRes);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  LightSensor.begin(); 
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();
pinMode(LED_BUILTIN, OUTPUT);

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  uint16_t lux = LightSensor.GetLightIntensity();
  delay(1000);
  
  float intensity =lux;
  
  if(intensity >200) sunlight = true;
  else sunlight = false;
  onLightChange();
}


/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
  
  digitalWrite(LED_BUILTIN, lED);
}
